sonata_user:
    resetting:
        email:
            address: '%env(NOTIFIER_EMAIL_FROM_ADDRESS)%'
            sender_name: '%env(EMAIL_STORIS_ORDER_SITE_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    sonata.user.user_provider.username_email:
        alias: Sonata\UserBundle\Security\UserProvider

    Sonata\UserBundle\Security\UserProvider:

    Sonata\UserBundle\Model\UserManagerInterface:
        alias: sonata.user.manager.user
