variables:
#    STAGE_SSH_HOST: $STAGE_SSH_HOST
#    STAGE_SSH_USER: $STAGE_SSH_USER
#    STAGE_SSH_PRIVATE_KEY: $STAGE_SSH_PRIVATE_KEY
    PROD_SSH_HOST: $PROD_SSH_HOST
    PROD_SSH_USER: $PROD_SSH_USER
    PROD_SSH_PRIVATE_KEY: $PROD_SSH_PRIVATE_KEY

include:
    - template: Auto-DevOps.gitlab-ci.yml

# https://gitlab.com/gitlab-cd/ssh-template/-/blob/master/ssh.yml
# https://gitlab.com/gitlab-examples/ssh-private-key/-/issues/4#note_35042568
.ssh_helper: &ssh_helper |
    function ssh_init() {
        SSH_PRIVATE_KEY="$1"
        SSH_KNOWN_HOSTS="$2"
        test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
        test -n "$SSH_KNOWN_HOSTS" || ( echo "missing variable SSH_KNOWN_HOSTS" && exit 1)
        which ssh-agent || ( apk update && apk add openssh-client )
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    }

    function ssh_run() {
        USER=$1
        HOST=$2
        PKEY=$3
        COMMAND=$4
        ssh_init "$PKEY" $HOST
        ssh $USER@$HOST $COMMAND
    }

test:
    image: gliderlabs/herokuish:latest-22

#deploy_staging:
#    stage: deploy
#    script:
#        - *ssh_helper
#        - ssh_run "$STAGE_SSH_USER" "$STAGE_SSH_HOST" "$STAGE_SSH_PRIVATE_KEY" "./deploy_middleware_staging.sh"
#    only:
#        - main
#        - develop

deploy_production:
    stage: deploy
    script:
        - *ssh_helper
        - ssh_run "$PROD_SSH_USER" "$PROD_SSH_HOST" "$PROD_SSH_PRIVATE_KEY" "./deploy_middleware.sh"
    only:
        - main
    when: manual
