<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Sonata\Doctrine\Bridge\Symfony\SonataDoctrineBundle::class => ['all' => true],
    Sonata\Twig\Bridge\Symfony\SonataTwigBundle::class => ['all' => true],
    Sonata\Form\Bridge\Symfony\SonataFormBundle::class => ['all' => true],
    Sonata\Exporter\Bridge\Symfony\SonataExporterBundle::class => ['all' => true],
    Sonata\BlockBundle\SonataBlockBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Sonata\AdminBundle\SonataAdminBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareBundle\EndertechEcommerceMiddlewareBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareNotificationBundle\EndertechEcommerceMiddlewareNotificationBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareAdminBundle\EndertechEcommerceMiddlewareAdminBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareDriverShopifyBundle\EndertechEcommerceMiddlewareDriverShopifyBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareDriverStorisBundle\EndertechEcommerceMiddlewareDriverStorisBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareShopifyStorisBundle\EndertechEcommerceMiddlewareShopifyStorisBundle::class => ['all' => true],
    Sonata\UserBundle\SonataUserBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareUserAdminBundle\EndertechEcommerceMiddlewareUserAdminBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareVariantAdminBundle\EndertechEcommerceMiddlewareVariantAdminBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareEventsBundle\EndertechEcommerceMiddlewareEventsBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareNotificationEventsBundle\EndertechEcommerceMiddlewareNotificationEventsBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareAdminEventsBundle\EndertechEcommerceMiddlewareAdminEventsBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareDriverShopifyEventsBundle\EndertechEcommerceMiddlewareDriverShopifyEventsBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareDriverStorisEventsBundle\EndertechEcommerceMiddlewareDriverStorisEventsBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareShopifyStorisEventsBundle\EndertechEcommerceMiddlewareShopifyStorisEventsBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareReportMetafieldBundle\EndertechEcommerceMiddlewareReportMetafieldBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareReportMetafieldAdminBundle\EndertechEcommerceMiddlewareReportMetafieldAdminBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareReportInventoryBundle\EndertechEcommerceMiddlewareReportInventoryBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareReportInventoryAdminBundle\EndertechEcommerceMiddlewareReportInventoryAdminBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareReportPriceBundle\EndertechEcommerceMiddlewareReportPriceBundle::class => ['all' => true],
    Endertech\EcommerceMiddlewareReportPriceAdminBundle\EndertechEcommerceMiddlewareReportPriceAdminBundle::class => ['all' => true],
    Webauthn\Stimulus\WebauthnStimulusBundle::class => ['all' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Webauthn\Bundle\WebauthnBundle::class => ['all' => true],
    Endertech\WebauthnBundle\EndertechWebauthnBundle::class => ['all' => true],
    Endertech\SonataUserWebauthnBundle\EndertechSonataUserWebauthnBundle::class => ['all' => true],
    Bazinga\GeocoderBundle\BazingaGeocoderBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
];
